/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package excerciseone.GUI;

import excerciseone.BLL.Common;
import excerciseone.BLL.Frm0003BLL;
import excerciseone.DTO.AccountSchoolDTO;
import excerciseone.DTO.StudentsWithPointDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Map;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author peter
 */
public class frm0003 extends javax.swing.JFrame {

    private AccountSchoolDTO accurent;
    
    /**
     * Creates new form frm0002
     */
    public frm0003() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        timecurrents = new javax.swing.JLabel();
        btnchangepass = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        jpannelviewpointsubject = new javax.swing.JPanel();
        labelviewpointsubject = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        DefaultTableModel modeltablepointsubject= new DefaultTableModel(){
            public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        modeltablepointsubject.addColumn("STT");
        modeltablepointsubject.addColumn("MSSV");
        modeltablepointsubject.addColumn("FULL NAME");
        modeltablepointsubject.addColumn("POINT MID");
        modeltablepointsubject.addColumn("POINT FINAL");
        modeltablepointsubject.addColumn("POINT DIFFERENCE");
        modeltablepointsubject.addColumn("POINT SUMMARY");
        modeltablepointsubject.addColumn("STATUS");
        tablepointsubject = new javax.swing.JTable(modeltablepointsubject);
        cbxpointsubject = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Management Study");
        setLocation(new java.awt.Point(150, 50));
        setPreferredSize(new java.awt.Dimension(1024, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(129, 211, 227));
        jPanel1.setPreferredSize(new java.awt.Dimension(831, 427));

        timecurrents.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        timecurrents.setText("0000-00-00 00:00:00 ");

        btnchangepass.setBackground(new java.awt.Color(220, 204, 96));
        btnchangepass.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnchangepass.setText("Change password");
        btnchangepass.setName("btnchangepass"); // NOI18N
        btnchangepass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnchangepassMouseClicked(evt);
            }
        });

        btnlogout.setBackground(new java.awt.Color(124, 121, 102));
        btnlogout.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.setName("btnchangepass"); // NOI18N
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnlogoutMousePressed(evt);
            }
        });

        username.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(195, 37, 39));
        username.setText("Name");

        jpannelviewpointsubject.setBackground(new java.awt.Color(129, 211, 227));
        jpannelviewpointsubject.setPreferredSize(new java.awt.Dimension(1024, 500));

        labelviewpointsubject.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelviewpointsubject.setText("Point of Subject: ");

        jScrollPane4.setViewportView(tablepointsubject);

        cbxpointsubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxpointsubject.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxpointsubjectItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jpannelviewpointsubjectLayout = new javax.swing.GroupLayout(jpannelviewpointsubject);
        jpannelviewpointsubject.setLayout(jpannelviewpointsubjectLayout);
        jpannelviewpointsubjectLayout.setHorizontalGroup(
            jpannelviewpointsubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpannelviewpointsubjectLayout.createSequentialGroup()
                .addComponent(labelviewpointsubject, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxpointsubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        jpannelviewpointsubjectLayout.setVerticalGroup(
            jpannelviewpointsubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpannelviewpointsubjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpannelviewpointsubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelviewpointsubject)
                    .addComponent(cbxpointsubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(timecurrents)
                .addGap(212, 212, 212)
                .addComponent(btnchangepass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnlogout)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpannelviewpointsubject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnlogout)
                        .addComponent(btnchangepass)
                        .addComponent(timecurrents))
                    .addComponent(username))
                .addContainerGap(529, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 47, Short.MAX_VALUE)
                    .addComponent(jpannelviewpointsubject, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMousePressed
        // TODO add your handling code here:
        // this.setOpacity(0.8f);
        this.setEnabled(false);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        frmlogout frmlogout= new frmlogout();
        frmlogout.setVisible(true);
        frmlogout.setAlwaysOnTop(true);
        frmlogout.setAccountSchool(accurent);
        frmlogout.setFrm0003s(this);
    }//GEN-LAST:event_btnlogoutMousePressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

            // TODO add your handling code here:
            
            Common com= new Common();
            ActionListener updateClockAction = new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        timecurrents.setText(com.getTimeCurrent());
                      }
            };
            Timer t = new Timer(1000, updateClockAction);
            t.start();
            username.setText(accurent.getNameshow());
            
            
            Frm0003BLL frm3= new Frm0003BLL();
            frm3.getAllPointOfStudent(this.accurent.getNamelogin());
            cbxpointsubject.removeAllItems();
            for(Map.Entry i : frm3.getPointstudent().entrySet()){
                cbxpointsubject.addItem(i.getKey().toString());
            }
            
            
//            Thread abc= new Thread(new Runnable() {
//                @Override
//                public void run() {
//                        timecurrents.setText(com.getTimeCurrent());             
//                }
//            });
//            while(true){
//                abc.start();
//                try {
//                    Thread.sleep(1000);
//                } catch (InterruptedException ex) {
//                    Logger.getLogger(frm0003.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
            
            
    }//GEN-LAST:event_formWindowActivated

    private void btnchangepassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnchangepassMouseClicked
           this.setEnabled(false);
           this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
           frmchangepassword frmchange= new frmchangepassword();
           frmchange.setVisible(true);
           frmchange.setAlwaysOnTop(true);
           frmchange.setAccountschool(accurent);
           frmchange.setFrm0003s(this);
    }//GEN-LAST:event_btnchangepassMouseClicked

    private void cbxpointsubjectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxpointsubjectItemStateChanged
        // TODO add your handling code here:
         if(cbxpointsubject.getSelectedItem()!=null){
              Frm0003BLL frm3= new Frm0003BLL();
              DefaultTableModel mo= (DefaultTableModel) tablepointsubject.getModel();
              mo.setRowCount(0);
                for(Map.Entry i : frm3.getPointstudent().entrySet()){
                    if(cbxpointsubject.getSelectedItem().toString().equals(i.getKey())){
                        StudentsWithPointDTO ss=(StudentsWithPointDTO) i.getValue();
                        Vector as= new Vector();
                        as.add(1);
                        as.add(ss.getMssv());
                        as.add(ss.getNamestudent());
                        as.add(ss.getPointmid());
                        as.add(ss.getPointfinal());
                        as.add(ss.getPointdifference());
                        as.add(ss.getPointsummary());
                        if(ss.getPointsummary()>=5){
                            as.add("Passed");
                        }else{
                            as.add("Falsed");
                        }
                        mo.addRow(as);
                        break;
                    }
                }
         }
    }//GEN-LAST:event_cbxpointsubjectItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm0003.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm0003.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm0003.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm0003.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm0003().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchangepass;
    private javax.swing.JButton btnlogout;
    private javax.swing.JComboBox<String> cbxpointsubject;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel jpannelviewpointsubject;
    private javax.swing.JLabel labelviewpointsubject;
    private javax.swing.JTable tablepointsubject;
    private javax.swing.JLabel timecurrents;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the accurent
     */
    public AccountSchoolDTO getAccurent() {
        return accurent;
    }

    /**
     * @param accurent the accurent to set
     */
    public void setAccurent(AccountSchoolDTO accurent) {
        this.accurent = accurent;
    }
}
