/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package excerciseone.GUI;

import excerciseone.DAL.FileDAL;
import excerciseone.DAL.StudentsWithPointDAL;
import excerciseone.DAL.SubjectsWithClassroomDAL;
import excerciseone.DTO.StudentsWithPointDTO;
import java.awt.Color;
import java.util.Iterator;
import java.util.LinkedList;

/**
 *
 * @author peter
 */
public class frmchangepoint extends javax.swing.JFrame {
    private frm0002 frm = new frm0002();
     private String nameclass;
     private StudentsWithPointDTO stu;
    /**
     * Creates new form frmAddStudents
     */
    public frmchangepoint() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbxpointdiff = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnokchangepoint = new javax.swing.JButton();
        btncancelpoint = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelmssv = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelerror = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelfullname = new javax.swing.JLabel();
        cbxpointmid = new javax.swing.JComboBox<>();
        cbxpointfinal = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        labelpointsum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(129, 211, 227));
        jPanel1.setPreferredSize(new java.awt.Dimension(447, 318));
        jPanel1.setRequestFocusEnabled(false);

        cbxpointdiff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nu", "Nam" }));
        cbxpointdiff.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxpointdiffItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("Mssv:");

        btnokchangepoint.setBackground(new java.awt.Color(241, 215, 36));
        btnokchangepoint.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnokchangepoint.setText("OK");
        btnokchangepoint.setName("btnlogin"); // NOI18N
        btnokchangepoint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnokchangepointMouseClicked(evt);
            }
        });

        btncancelpoint.setBackground(new java.awt.Color(195, 190, 152));
        btncancelpoint.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btncancelpoint.setText("Cancel");
        btncancelpoint.setName("btnlogin"); // NOI18N
        btncancelpoint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelpointMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("Full Name:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("Point final:");

        labelmssv.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelmssv.setForeground(new java.awt.Color(1, 1, 1));
        labelmssv.setText("3423432");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(1, 1, 1));
        jLabel6.setText("Point mid:");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 1, 1));
        jLabel7.setText("Point sum");

        labelerror.setBackground(new java.awt.Color(176, 34, 44));
        labelerror.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        labelerror.setForeground(new java.awt.Color(188, 39, 39));
        labelerror.setText("Error not add in to class");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(1, 1, 1));
        jLabel9.setText("Change point of Student");

        labelfullname.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelfullname.setForeground(new java.awt.Color(1, 1, 1));
        labelfullname.setText("none");

        cbxpointmid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nu", "Nam" }));
        cbxpointmid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxpointmidItemStateChanged(evt);
            }
        });

        cbxpointfinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nu", "Nam" }));
        cbxpointfinal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxpointfinalItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(1, 1, 1));
        jLabel8.setText("Point diff");

        labelpointsum.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelpointsum.setForeground(new java.awt.Color(1, 1, 1));
        labelpointsum.setText("123456");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnokchangepoint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncancelpoint)
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelerror)
                            .addComponent(cbxpointdiff, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelmssv)
                            .addComponent(labelfullname)
                            .addComponent(cbxpointmid, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxpointfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelpointsum))
                        .addContainerGap(64, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(4, 4, 4)
                .addComponent(labelerror)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelmssv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelfullname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxpointmid, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxpointfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxpointdiff, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelpointsum))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnokchangepoint)
                    .addComponent(btncancelpoint))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnokchangepointMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnokchangepointMouseClicked
        // TODO add your handling code here:
        String names=this.nameclass+"_P";
        String path=FileDAL.getPathFile(names);
        SubjectsWithClassroomDAL dal= new SubjectsWithClassroomDAL();
        LinkedList<StudentsWithPointDTO> dss= dal.getPointSubjectsWithClassroomByPath(path);
        stu.setPointmid(Integer.valueOf(cbxpointmid.getSelectedItem().toString()));
        stu.setPointfinal(Integer.valueOf(cbxpointfinal.getSelectedItem().toString()));
        stu.setPointdifference(Integer.valueOf(cbxpointdiff.getSelectedItem().toString()));
        stu.setPointsummary(Integer.valueOf(labelpointsum.getText()));
        if(dss != null){
            Iterator<StudentsWithPointDTO> in= dss.iterator();
            while(in.hasNext()){
                StudentsWithPointDTO s=in.next();
                if(s.getMssv().equals(stu.getMssv())){
                    s.setPointmid(stu.getPointmid());
                    s.setPointfinal(stu.getPointfinal());
                    s.setPointdifference(stu.getPointdifference());
                    s.setPointsummary(stu.getPointsummary());
                    break;
                }
            }
            StudentsWithPointDAL sdal= new StudentsWithPointDAL();
            if(!sdal.writePointSubjectsWithClassroomByPath(dss, names)){
                labelerror.setText("Error when import point");
                labelerror.setVisible(true);
                labelerror.setForeground(Color.red);
            }else{
               labelerror.setText("Change point success ");
                labelerror.setVisible(true);
                labelerror.setForeground(Color.BLUE); 
                frm.loadcbxpointsubjectItemStateChanged();
                
            }
        }
        
    }//GEN-LAST:event_btnokchangepointMouseClicked

    private void btncancelpointMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelpointMouseClicked
        // TODO add your handling code here:
        
        this.dispose();

    }//GEN-LAST:event_btncancelpointMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        labelerror.setVisible(false);
       labelmssv.setText(stu.getMssv());
       labelfullname.setText(stu.getNamestudent());
       cbxpointmid.removeAllItems();
       cbxpointfinal.removeAllItems();
       cbxpointdiff.removeAllItems();
       for(int i=1;i<=10;i++){
           cbxpointmid.addItem(String.valueOf(i));
           cbxpointfinal.addItem(String.valueOf(i));
           cbxpointdiff.addItem(String.valueOf(i));
       }
       cbxpointmid.setSelectedItem(String.valueOf(stu.getPointmid()));
       cbxpointfinal.setSelectedItem(String.valueOf(stu.getPointfinal()));
       cbxpointdiff.setSelectedItem(String.valueOf(stu.getPointdifference()));
       float pmid=Integer.valueOf(cbxpointmid.getSelectedItem().toString())*30;
       float pmfi=Integer.valueOf(cbxpointfinal.getSelectedItem().toString())*60;
       float pmdiff=Integer.valueOf(cbxpointdiff.getSelectedItem().toString())*10;
       int sum=(int)(pmid+pmfi+pmdiff)/100;
       labelpointsum.setText(String.valueOf(sum));
    }//GEN-LAST:event_formWindowActivated

    private void cbxpointmidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxpointmidItemStateChanged
        // TODO add your handling code here:
       udpatePoint();    
    }//GEN-LAST:event_cbxpointmidItemStateChanged

    private void cbxpointfinalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxpointfinalItemStateChanged
        // TODO add your handling code here:
      udpatePoint();
    }//GEN-LAST:event_cbxpointfinalItemStateChanged

    private void cbxpointdiffItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxpointdiffItemStateChanged
        // TODO add your handling code here:
       udpatePoint();
    }//GEN-LAST:event_cbxpointdiffItemStateChanged

    void udpatePoint(){
        if(cbxpointfinal.getSelectedItem() !=null && cbxpointmid.getSelectedItem() !=null &&
                cbxpointdiff.getSelectedItem() !=null){
            float pmid=Integer.valueOf(cbxpointmid.getSelectedItem().toString())*30;
           float pmfi=Integer.valueOf(cbxpointfinal.getSelectedItem().toString())*60;
           float pmdiff=Integer.valueOf(cbxpointdiff.getSelectedItem().toString())*10;
           int sum=(int)(pmid+pmfi+pmdiff)/100;
           labelpointsum.setText(String.valueOf(sum));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmchangepoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmchangepoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmchangepoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmchangepoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmchangepoint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelpoint;
    private javax.swing.JButton btnokchangepoint;
    private javax.swing.JComboBox<String> cbxpointdiff;
    private javax.swing.JComboBox<String> cbxpointfinal;
    private javax.swing.JComboBox<String> cbxpointmid;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelerror;
    private javax.swing.JLabel labelfullname;
    private javax.swing.JLabel labelmssv;
    private javax.swing.JLabel labelpointsum;
    // End of variables declaration//GEN-END:variables

    
    /**
     * @return the nameclass
     */
    public String getNameclass() {
        return nameclass;
    }

    /**
     * @param nameclass the nameclass to set
     */
    public void setNameclass(String nameclass) {
        this.nameclass = nameclass;
    }

    /**
     * @return the stu
     */
    public StudentsWithPointDTO getStu() {
        return stu;
    }

    /**
     * @param stu the stu to set
     */
    public void setStu(StudentsWithPointDTO stu) {
        this.stu = stu;
    }

    /**
     * @return the frm
     */
    public frm0002 getFrm() {
        return frm;
    }

    /**
     * @param frm the frm to set
     */
    public void setFrm(frm0002 frm) {
        this.frm = frm;
    }

    
}  
