/*
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package excerciseone.GUI;

import excerciseone.BLL.Frm0002BLL;
import excerciseone.DTO.ClassRoomDTO;
import excerciseone.DTO.StudentsDTO;
import java.awt.Color;
import java.util.LinkedList;
import java.util.Map;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author peter
 */
public class frmchangestudy extends javax.swing.JFrame {

    private Map<String,String> mapmaxmssvclass;
    /**
     * Creates new form frmAddStudents
     */
    public frmchangestudy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbxallclassroom = new javax.swing.JComboBox<>();
        cbxsexaddstudent = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnokaddstudent = new javax.swing.JButton();
        btncanceladdstudent = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelgenaratemssvaddstudnet = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnamestudentadd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        labelerror = new javax.swing.JLabel();
        txtidentityaddstudent = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(129, 211, 227));
        jPanel1.setPreferredSize(new java.awt.Dimension(447, 318));
        jPanel1.setRequestFocusEnabled(false);

        cbxallclassroom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxallclassroom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxallclassroomItemStateChanged(evt);
            }
        });

        cbxsexaddstudent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nu", "Nam" }));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("Class Study");

        btnokaddstudent.setBackground(new java.awt.Color(241, 215, 36));
        btnokaddstudent.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnokaddstudent.setText("OK");
        btnokaddstudent.setName("btnlogin"); // NOI18N
        btnokaddstudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnokaddstudentMouseClicked(evt);
            }
        });

        btncanceladdstudent.setBackground(new java.awt.Color(195, 190, 152));
        btncanceladdstudent.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btncanceladdstudent.setText("Cancel");
        btncanceladdstudent.setName("btnlogin"); // NOI18N
        btncanceladdstudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncanceladdstudentMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("Full Name");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("Identity");

        labelgenaratemssvaddstudnet.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelgenaratemssvaddstudnet.setForeground(new java.awt.Color(1, 1, 1));
        labelgenaratemssvaddstudnet.setText("123456");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(1, 1, 1));
        jLabel6.setText("Sex");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 1, 1));
        jLabel7.setText("MSSV (Auto Gen)");

        labelerror.setBackground(new java.awt.Color(176, 34, 44));
        labelerror.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        labelerror.setForeground(new java.awt.Color(188, 39, 39));
        labelerror.setText("Error not add in to class");

        txtidentityaddstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidentityaddstudentActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(1, 1, 1));
        jLabel9.setText("Change study for Student");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelerror)
                            .addComponent(cbxsexaddstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtnamestudentadd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbxallclassroom, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtidentityaddstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelgenaratemssvaddstudnet))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnokaddstudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncanceladdstudent)
                        .addGap(69, 69, 69))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(4, 4, 4)
                .addComponent(labelerror)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxallclassroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnamestudentadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxsexaddstudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtidentityaddstudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelgenaratemssvaddstudnet)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnokaddstudent)
                    .addComponent(btncanceladdstudent))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnokaddstudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnokaddstudentMouseClicked
        // TODO add your handling code here:
        if(!StringUtils.isNotBlank(txtnamestudentadd.getText())){
            labelerror.setText(" Name of Student Null");
            labelerror.setVisible(true);
            return ;
        }
        if(!StringUtils.isNotBlank(txtidentityaddstudent.getText())){
            labelerror.setText("Identoty of Student Null");
            labelerror.setVisible(true);
            return ;
        }
        if(!StringUtils.isNumeric(txtidentityaddstudent.getText())){
            labelerror.setText("Identoty is Not Number");
            labelerror.setVisible(true);
            return ;
        }
        String [] ds= new String[]{
            labelgenaratemssvaddstudnet.getText(),
            txtnamestudentadd.getText(),
            cbxsexaddstudent.getSelectedItem().toString(),
            txtidentityaddstudent.getText()
        };
        StudentsDTO stu= new StudentsDTO(ds);
        Frm0002BLL.getAllClassRoom();
        LinkedList<ClassRoomDTO> colClassRooms=Frm0002BLL.getColClassRoom();
        for(ClassRoomDTO i:colClassRooms){
            if(i.getNameroom().equals(cbxallclassroom.getSelectedItem().toString())){
                i.getCollectionSTU().add(stu);
                Frm0002BLL fr= new Frm0002BLL();
                boolean ff= fr.writeStudentsClass(i);
                if(ff){
                    labelerror.setVisible(true);
                    labelerror.setText("Save success Student");
                    labelerror.setForeground(Color.BLUE);
                    txtidentityaddstudent.setText("");
                    txtnamestudentadd.setText("");
                    labelgenaratemssvaddstudnet.setText("");
                }else{
                    labelerror.setText("Error Not Save !!! ");
                    labelerror.setVisible(true);
                }
                return;
            }
        }
    }//GEN-LAST:event_btnokaddstudentMouseClicked

    private void btncanceladdstudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncanceladdstudentMouseClicked
        // TODO add your handling code here:
        
        this.dispose();

    }//GEN-LAST:event_btncanceladdstudentMouseClicked

    private void txtidentityaddstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidentityaddstudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidentityaddstudentActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        cbxallclassroom.removeAllItems();
        labelgenaratemssvaddstudnet.setText("null");
        for(Map.Entry m:mapmaxmssvclass.entrySet()){
            cbxallclassroom.addItem((String) m.getKey());
        }
        labelerror.setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    private void cbxallclassroomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxallclassroomItemStateChanged
        // TODO add your handling code here:
        if(cbxallclassroom.getSelectedItem() != null){
            for(Map.Entry m:mapmaxmssvclass.entrySet()){
                if(cbxallclassroom.getSelectedItem().toString().equals(m.getKey())){
                    labelgenaratemssvaddstudnet.setText((String) m.getValue());
                }
            }
        }
    }//GEN-LAST:event_cbxallclassroomItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmchangestudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmchangestudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmchangestudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmchangestudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmchangestudy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncanceladdstudent;
    private javax.swing.JButton btnokaddstudent;
    private javax.swing.JComboBox<String> cbxallclassroom;
    private javax.swing.JComboBox<String> cbxsexaddstudent;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelerror;
    private javax.swing.JLabel labelgenaratemssvaddstudnet;
    private javax.swing.JTextField txtidentityaddstudent;
    private javax.swing.JTextField txtnamestudentadd;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the mapmaxmssvclass
     */
    public Map<String,String> getMapmaxmssvclass() {
        return mapmaxmssvclass;
    }

    /**
     * @param mapmaxmssvclass the mapmaxmssvclass to set
     */
    public void setMapmaxmssvclass(Map<String,String> mapmaxmssvclass) {
        this.mapmaxmssvclass = mapmaxmssvclass;
    }

    
}  
