/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package excerciseone.GUI;

import excerciseone.BLL.Frm0002BLL;
import excerciseone.DAL.SubjectsWithClassroomDAL;
import excerciseone.DTO.ClassRoomDTO;
import excerciseone.DTO.StudentsDTO;
import excerciseone.DTO.SubjectsWithClassroomDTO;
import java.awt.Color;
import java.util.Iterator;
import java.util.LinkedList;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author peter
 */
public class frmmanageclass extends javax.swing.JFrame {
    private String nameclass;
    private frm0002 frm0002s;
    private StudentsDTO stu;
    
    /**
     * Creates new form frmAddStudents
     */
    public frmmanageclass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnokaddstudent = new javax.swing.JButton();
        btncanceladdstudent = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelstatus = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelstudents = new javax.swing.JLabel();
        cbxncodestudents = new javax.swing.JComboBox<>();
        cbxcodeclass = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(129, 211, 227));
        jPanel1.setPreferredSize(new java.awt.Dimension(447, 318));
        jPanel1.setRequestFocusEnabled(false);

        btnokaddstudent.setBackground(new java.awt.Color(241, 215, 36));
        btnokaddstudent.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnokaddstudent.setText("OK");
        btnokaddstudent.setName("btnlogin"); // NOI18N
        btnokaddstudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnokaddstudentMouseClicked(evt);
            }
        });

        btncanceladdstudent.setBackground(new java.awt.Color(195, 190, 152));
        btncanceladdstudent.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btncanceladdstudent.setText("Cancel");
        btncanceladdstudent.setName("btnlogin"); // NOI18N
        btncanceladdstudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncanceladdstudentMouseClicked(evt);
            }
        });
        btncanceladdstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncanceladdstudentActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("Full Name");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("Class");

        labelstatus.setBackground(new java.awt.Color(176, 34, 44));
        labelstatus.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        labelstatus.setForeground(new java.awt.Color(188, 39, 39));
        labelstatus.setText("Error not add student");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(1, 1, 1));
        jLabel9.setText("Add student into Class");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 1, 1));
        jLabel5.setText("MSSV");

        labelstudents.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelstudents.setForeground(new java.awt.Color(1, 1, 1));
        labelstudents.setText("Class Study");

        cbxncodestudents.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nu", "Nam" }));
        cbxncodestudents.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxncodestudentsItemStateChanged(evt);
            }
        });

        cbxcodeclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nu", "Nam" }));
        cbxcodeclass.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxcodeclassItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelstatus)
                    .addComponent(cbxcodeclass, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnokaddstudent)
                        .addGap(57, 57, 57)
                        .addComponent(btncanceladdstudent))
                    .addComponent(cbxncodestudents, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelstudents, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelstatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxcodeclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxncodestudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelstudents)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnokaddstudent)
                    .addComponent(btncanceladdstudent))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnokaddstudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnokaddstudentMouseClicked
        // TODO add your handling code here:
        if(!StringUtils.isNotBlank(cbxcodeclass.getSelectedItem().toString())){
            labelstatus.setText("Class NUll");
            labelstatus.setVisible(true);
            return;
        }
        if(!StringUtils.isNotBlank(cbxncodestudents.getSelectedItem().toString())){
            labelstatus.setText("Student NUll");
            labelstatus.setVisible(true);
            return;
        }
        // luu vao clop hien tai
        System.out.println(stu.getMssv()+" "+stu.getName());
        SubjectsWithClassroomDTO ds =null;
        Iterator<SubjectsWithClassroomDTO> in= Frm0002BLL.getColSubPointStuent().iterator();
        while(in.hasNext()){
            SubjectsWithClassroomDTO ob=in.next();
            String name=ob.getNameroom()+"_"+ob.getCodesubject();
            if(name.equals(nameclass)){
                ds= new SubjectsWithClassroomDTO(ob);
                break;
            }
        }
        LinkedList<StudentsDTO> dss=ds.getCollectionstudent();
        for(StudentsDTO i:dss){
           if(i.getMssv().equals(stu.getMssv())){
               labelstatus.setText("Mssv Contain in Class !");
               labelstatus.setVisible(true);
               return;
           } 
        }
        dss.add(stu);
        ds.setCollectionstudent(dss);
        SubjectsWithClassroomDAL subdal= new SubjectsWithClassroomDAL();
        if(subdal.writeSubjectWithStudent(ds)){
            labelstatus.setText("Mssv add success !");
            labelstatus.setVisible(true);
            labelstatus.setForeground(Color.BLUE);
            cbxcodeclass.setSelectedIndex(0);
            frm0002s.loadcbxstudentsubject();
            return ;
        }
        labelstatus.setForeground(Color.red);
         labelstatus.setText("Mssv Not add  !");
         labelstatus.setVisible(true);
    }//GEN-LAST:event_btnokaddstudentMouseClicked

    private void btncanceladdstudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncanceladdstudentMouseClicked
        // TODO add your handling code here:
        
        this.dispose();

    }//GEN-LAST:event_btncanceladdstudentMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        labelstatus.setVisible(false);
        Frm0002BLL.getAllClassRoom();
        LinkedList<ClassRoomDTO> colcr=Frm0002BLL.getColClassRoom();
        cbxcodeclass.removeAllItems();
        for(ClassRoomDTO i:colcr){
            cbxcodeclass.addItem(i.getNameroom());
        }
    }//GEN-LAST:event_formWindowActivated

    private void btncanceladdstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncanceladdstudentActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncanceladdstudentActionPerformed

    private void cbxcodeclassItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxcodeclassItemStateChanged
        // TODO add your handling code here:
        if(cbxcodeclass.getSelectedItem()!=null){
            Frm0002BLL.getAllClassRoom();
            LinkedList<ClassRoomDTO> colcr=Frm0002BLL.getColClassRoom();
            cbxncodestudents.removeAllItems();
            for(ClassRoomDTO i:colcr){
                if(i.getNameroom().equals(cbxcodeclass.getSelectedItem().toString())){
                    for(StudentsDTO j:i.getCollectionSTU()){
                        cbxncodestudents.addItem(j.getMssv());
                    }
                    return;
                }
            }
        }
    }//GEN-LAST:event_cbxcodeclassItemStateChanged

    private void cbxncodestudentsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxncodestudentsItemStateChanged
        // TODO add your handling code here:
        if(cbxncodestudents.getSelectedItem()!=null){
            Frm0002BLL.getAllClassRoom();
            LinkedList<ClassRoomDTO> colcr=Frm0002BLL.getColClassRoom();
            for(ClassRoomDTO i:colcr){
                if(i.getNameroom().equals(cbxcodeclass.getSelectedItem().toString())){
                    for(StudentsDTO j:i.getCollectionSTU()){
                        if(cbxncodestudents.getSelectedItem().toString().equals(j.getMssv())){
                            stu= new StudentsDTO(
                            j.getMssv(),j.getName(),j.getSex(),j.getIdentity());
                            labelstudents.setText(j.getName());
                            return;
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_cbxncodestudentsItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmmanageclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmmanageclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmmanageclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmmanageclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmmanageclass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncanceladdstudent;
    private javax.swing.JButton btnokaddstudent;
    private javax.swing.JComboBox<String> cbxcodeclass;
    private javax.swing.JComboBox<String> cbxncodestudents;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelstatus;
    private javax.swing.JLabel labelstudents;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the nameclass
     */
    public String getNameclass() {
        return nameclass;
    }

    /**
     * @param nameclass the nameclass to set
     */
    public void setNameclass(String nameclass) {
        this.nameclass = nameclass;
    }

    /**
     * @return the frm0002s
     */
    public frm0002 getFrm0002s() {
        return frm0002s;
    }

    /**
     * @param frm0002s the frm0002s to set
     */
    public void setFrm0002s(frm0002 frm0002s) {
        this.frm0002s = frm0002s;
    }

    /**
     * @return the stu
     */
    public StudentsDTO getStu() {
        return stu;
    }

    /**
     * @param stu the stu to set
     */
    public void setStu(StudentsDTO stu) {
        this.stu = stu;
    }

     
    
}  
